#!/bin/sh
#
# Workaround for missing +x bits in initial CVS import.
#
chmod a+x src/gcc/config.guess
chmod a+x src/gcc/config.sub
chmod a+x src/gcc/configure
chmod a+x src/gcc/install-sh
chmod a+x src/gcc/ltconfig
chmod a+x src/gcc/missing
chmod a+x src/gcc/mkdep
chmod a+x src/gcc/mkinstalldirs
chmod a+x src/gcc/move-if-change
chmod a+x src/gcc/symlink-tree
chmod a+x src/gcc/ylwrap
chmod a+x src/gcc/boehm-gc/callprocs
chmod a+x src/gcc/boehm-gc/config.guess
chmod a+x src/gcc/boehm-gc/config.sub
chmod a+x src/gcc/boehm-gc/configure
chmod a+x src/gcc/boehm-gc/install-sh
chmod a+x src/gcc/boehm-gc/ltconfig
chmod a+x src/gcc/boehm-gc/mkinstalldirs
chmod a+x src/gcc/contrib/analyze_brprob
chmod a+x src/gcc/contrib/compare_tests
chmod a+x src/gcc/contrib/convert_to_f2c
chmod a+x src/gcc/contrib/convert_to_g2c
chmod a+x src/gcc/contrib/download_f2c
chmod a+x src/gcc/contrib/gcc_build
chmod a+x src/gcc/contrib/gcc_update
chmod a+x src/gcc/contrib/gennews
chmod a+x src/gcc/contrib/index-prop
chmod a+x src/gcc/contrib/newcvsroot
chmod a+x src/gcc/contrib/test_installed
chmod a+x src/gcc/contrib/test_summary
chmod a+x src/gcc/contrib/texi2pod.pl
chmod a+x src/gcc/contrib/warn_summary
chmod a+x src/gcc/contrib/reghunt/reg_periodic
chmod a+x src/gcc/contrib/reghunt/reg_search
chmod a+x src/gcc/contrib/reghunt/reg_test_template
chmod a+x src/gcc/contrib/regression/btest-gcc.sh
chmod a+x src/gcc/contrib/regression/objs-gcc.sh
chmod a+x src/gcc/fastjar/configure
chmod a+x src/gcc/fastjar/install-sh
chmod a+x src/gcc/fastjar/missing
chmod a+x src/gcc/fastjar/mkinstalldirs
chmod a+x src/gcc/gcc/gccbug.in
chmod a+x src/gcc/gcc/doc/install.texi2html
chmod a+x src/gcc/gcc/fixinc/fixinc.svr4
chmod a+x src/gcc/gcc/fixinc/fixinc.wrap
chmod a+x src/gcc/gcc/fixinc/fixincl.sh
chmod a+x src/gcc/gcc/fixinc/genfixes
chmod a+x src/gcc/gcc/fixinc/mkfixinc.sh
chmod a+x src/gcc/gcc/intl/config.charset
chmod a+x src/gcc/gcc/testsuite/gcc.dg/dll-5.c
chmod a+x src/gcc/libf2c/libF77/configure
chmod a+x src/gcc/libf2c/configure
chmod a+x src/gcc/libf2c/libI77/configure
chmod a+x src/gcc/libf2c/libU77/configure
chmod a+x src/gcc/libffi/configure
chmod a+x src/gcc/libiberty/configure
chmod a+x src/gcc/libjava/addr2name.awk
chmod a+x src/gcc/libjava/configure
chmod a+x src/gcc/libjava/libltdl/configure
chmod a+x src/gcc/libjava/scripts/unicode-blocks.pl
chmod a+x src/gcc/libjava/scripts/unicode-decomp.pl
chmod a+x src/gcc/libjava/scripts/unicode-muncher.pl
chmod a+x src/gcc/libobjc/configure
chmod a+x src/gcc/libstdc++-v3/configure
chmod a+x src/gcc/libstdc++-v3/mkcheck.in
chmod a+x src/gcc/libstdc++-v3/testsuite_flags.in
chmod a+x src/gcc/libstdc++-v3/config/abi/extract_symvers
chmod a+x src/gcc/maintainer-scripts/gcc_release
chmod a+x src/gcc/maintainer-scripts/update_version
chmod a+x src/gcc/maintainer-scripts/update_web_docs
chmod a+x src/gcc/maintainer-scripts/update_web_docs_libstdcxx
chmod a+x src/gcc/maintainer-scripts/update_web_docs_old
chmod a+x src/gcc/zlib/configure
# binutils
chmod a+x src/binutils/bfd/config.bfd
chmod a+x src/binutils/bfd/configure
chmod a+x src/binutils/binutils/configure
chmod a+x src/binutils/binutils/ranlib.sh
chmod a+x src/binutils/binutils/sanity.sh
chmod a+x src/binutils/config/acinclude.m4
chmod a+x src/binutils/config.guess
chmod a+x src/binutils/config.sub
chmod a+x src/binutils/configure
chmod a+x src/binutils/etc/configure
chmod a+x src/binutils/gas/configure
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/align1.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/align2.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/block1.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/block2.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/calldatabug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/entrybug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/exportbug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/fixup7bug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/global.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/linesepbug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/lselbug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/nosubspace.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/parse.exp
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/procbug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/stringer.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/undefbug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/parse/versionbug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/reloc/blebug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/reloc/blebug2.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/reloc/blebug3.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/reloc/labelopbug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/reloc/plabelbug.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/reloc/reduce.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/reloc/reloc.exp
chmod a+x src/binutils/gas/testsuite/gas/hppa/unsorted/labeldiffs.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/unsorted/locallabel.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/unsorted/ss_align.s
chmod a+x src/binutils/gas/testsuite/gas/hppa/unsorted/unsorted.exp
chmod a+x src/binutils/gas/testsuite/lib/doboth
chmod a+x src/binutils/gas/testsuite/lib/doobjcmp
chmod a+x src/binutils/gas/testsuite/lib/dostriptest
chmod a+x src/binutils/gas/testsuite/lib/dotest
chmod a+x src/binutils/gas/testsuite/lib/dounsreloc
chmod a+x src/binutils/gas/testsuite/lib/dounssym
chmod a+x src/binutils/gas/testsuite/lib/run
chmod a+x src/binutils/gprof/bbconv.pl
chmod a+x src/binutils/gprof/configure
chmod a+x src/binutils/install-sh
chmod a+x src/binutils/intl/config.status
chmod a+x src/binutils/intl/configure
chmod a+x src/binutils/intl/linux-msg.sed
chmod a+x src/binutils/intl/po2tbl.sed.in
chmod a+x src/binutils/intl/xopen-msg.sed
chmod a+x src/binutils/ld/configure
chmod a+x src/binutils/ld/emulparams/elf32bmipn32.sh
chmod a+x src/binutils/ld/emulparams/elf32fr30.sh
chmod a+x src/binutils/ld/emulparams/elf64bmip.sh
chmod a+x src/binutils/ld/emulparams/elf64hppa.sh
chmod a+x src/binutils/ld/emulparams/i386beos.sh
chmod a+x src/binutils/ld/genscripts.sh
chmod a+x src/binutils/libiberty/configure
chmod a+x src/binutils/libiberty/testsuite/regress-demangle
chmod a+x src/binutils/ltconfig
chmod a+x src/binutils/missing
chmod a+x src/binutils/mkdep
chmod a+x src/binutils/mkinstalldirs
chmod a+x src/binutils/move-if-change
chmod a+x src/binutils/opcodes/configure
chmod a+x src/binutils/symlink-tree
chmod a+x src/binutils/ylwrap
# added by hand
chmod a+x src/gcc/gcc/mkoptdesc.sh
