/* sys/seterrno.c (emx+gcc) -- Copyright (c) 1992-1998 by Eberhard Mattes */

#include "libc-alias.h"
#include <errno.h>
#include "syscalls.h"
#include "backend.h"

#define __LIBC_LOG_GROUP __LIBC_LOG_GRP_NOGROUP
#include <InnoTekLIBC/logstrict.h>

static unsigned char const errno_tab[] =
{
  EINVAL, EINVAL, ENOENT, ENOENT, EMFILE,  /* 0..4 */
  EACCES, EBADF,  EIO,    ENOMEM, EIO,     /* 5..9 */
  EINVAL, ENOEXEC,EINVAL, EINVAL, EINVAL,  /* 10..14 */
  ENOENT, EBUSY,  EXDEV,  ENOENT, EROFS,   /* 15..19 */
  EIO,    EIO,    EIO,    EIO,    EIO,     /* 20..24 */
  EIO,    EIO,    EIO,    ENOSPC, EIO,     /* 25..29 */
  EIO,    EIO,    EACCES, EACCES, EIO,     /* 30..34 */
  EIO,    EIO,    EIO,    EIO,    ENOSPC,  /* 35..39 */
  EIO,    EIO,    EIO,    EIO,    EIO,     /* 40..44 */
  EIO,    EIO,    EIO,    EIO,    EIO,     /* 45..49 */
  EIO,    EIO,    EIO,    EIO,    EBUSY,   /* 50..54 */
  EIO,    EIO,    EIO,    EIO,    EIO,     /* 55..59 */
  EIO,    ENOSPC, ENOSPC, EIO,    EIO,     /* 60..64 */
  EACCES, EIO,    EIO,    EIO,    EIO,     /* 65..69 */
  EIO,    EIO,    EIO,    EROFS,  EIO,     /* 70..74 */
  EIO,    EIO,    EIO,    EIO,    EIO,     /* 75..79 */
  EEXIST, EIO,    ENOENT, EIO,    EIO,     /* 80..84 */
  EIO,    EIO,    EINVAL, EIO,    EAGAIN,  /* 85..89 */
  EIO,    EIO,    EIO,    EIO,    EIO,     /* 90..94 */
  EINTR,  EIO,    EIO,    EIO,    EACCES,  /* 95..99 */
  ENOMEM, EINVAL, EINVAL, ENOMEM, EINVAL,  /* 100..104 */
  EINVAL, ENOMEM, EIO,    EACCES, EPIPE,   /* 105..109 */
  ENOENT, E2BIG,  ENOSPC, ENOMEM, EBADF,   /* 110..114 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 115..119 */
  EINVAL, EINVAL, EINVAL, ENOENT, EINVAL,  /* 120..124 */
  ENOENT, ENOENT, ENOENT, ECHILD, ECHILD,  /* 125..129 */
  EACCES, EINVAL, ESPIPE, EINVAL, EINVAL,  /* 130..134 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 135..139 */
  EINVAL, EINVAL, EBUSY,  EINVAL, EINVAL,  /* 140..144 */
  EINVAL, EINVAL, EINVAL, EBUSY,  EINVAL,  /* 145..149 */
  EINVAL, EINVAL, ENOMEM, EINVAL, EINVAL,  /* 150..154 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 155..159 */
  EINVAL, EINVAL, EINVAL, EINVAL, EAGAIN,  /* 160..164 */
  EINVAL, EINVAL, EACCES, EINVAL, EINVAL,  /* 165..169 */
  EBUSY,  EINVAL, EINVAL, EINVAL, EINVAL,  /* 170..174 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 175..179 */
  EINVAL, EINVAL, EINVAL, EINVAL, ECHILD,  /* 180..184 */
  EINVAL, EINVAL, ENOENT, EINVAL, EINVAL,  /* 185..189 */
  ENOEXEC,ENOEXEC,ENOEXEC,ENOEXEC,ENOEXEC, /* 190..194 */
  ENOEXEC,ENOEXEC,ENOEXEC,ENOEXEC,ENOEXEC, /* 195..199 */
  ENOEXEC,ENOEXEC,ENOEXEC,ENOENT, EINVAL,  /* 200..204 */
  EINVAL, ENAMETOOLONG, EINVAL, EINVAL, EINVAL,  /* 205..209 */
  EINVAL, EINVAL, EACCES, ENOEXEC,ENOEXEC, /* 210..214 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 215..219 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 220..224 */
  EINVAL, EINVAL, EINVAL, ECHILD, EINVAL,  /* 225..229 */
  EINVAL, EBUSY,  EAGAIN, ENOTCONN, EINVAL, /* 230..234 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 235..239 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 240..244 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 245..249 */
  EACCES, EACCES, EINVAL, ENOENT, EINVAL,  /* 250..254 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 255..259 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 260..264 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 265..269 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 270..274 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 275..279 */
  EINVAL, EINVAL, ENOTSUP, EINVAL, EEXIST,  /* 280..284 */
  EEXIST, EINVAL, EINVAL, EINVAL, EINVAL,  /* 285..289 */
  ENOMEM, EMFILE, EINVAL, EINVAL, EINVAL,  /* 290..294 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 295..299 */
  EINVAL, EBUSY,  EINVAL, ESRCH,  EINVAL,  /* 300..304 */
  ESRCH,  EINVAL, EINVAL, EINVAL, ESRCH,   /* 305..309 */
  EINVAL, ENOMEM, EINVAL, EINVAL, EINVAL,  /* 310..314 */
  EINVAL, E2BIG,  ENOENT, EIO,    EIO,     /* 315..319 */
  EINVAL, EINVAL, EINVAL, EINVAL, EAGAIN,  /* 320..324 */
  EINVAL, EINVAL, EINVAL, EIO,    ENOENT,  /* 325..329 */
  EACCES, EACCES, EACCES, ENOENT, ENOMEM,  /* 330..334 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 335..339 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 340..344 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 345..349 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 350..354 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 355..359 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 360..364 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 365..369 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 370..374 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 375..379 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 380..384 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 385..389 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 390..394 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 395..399 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 400..404 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 405..409 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 410..414 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 415..419 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 420..424 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 425..429 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 430..434 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 435..439 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 440..444 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 445..449 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 450..454 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 455..459 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 460..464 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 465..469 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 470..474 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 475..479 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 480..484 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 485..489 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 490..494 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 495..499 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 500..504 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 505..509 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 510..514 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 515..519 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 520..524 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 525..529 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 530..534 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 535..539 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 540..544 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 545..549 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 550..554 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 555..559 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 560..564 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 565..569 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 570..574 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 575..579 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 580..584 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 585..589 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 590..594 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 595..599 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 600..604 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 605..609 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 610..614 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 615..619 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 620..624 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 625..629 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 630..634 */
  EINVAL, EINVAL, EINVAL, EINVAL, EINVAL,  /* 635..639 */
  ETIMEDOUT, EINVAL, EINVAL, EINVAL, EINVAL,  /* 640..644 */
};


void _sys_set_errno (unsigned long rc)
{
  if (rc >= sizeof (errno_tab))
    errno = EINVAL;
  else
    errno = errno_tab[rc];
  LIBCLOG_MSG2("Set errno %d for OS/2 error %ld\n", errno, rc);
}

int __libc_native2errno (unsigned long rc)
{
  if (rc >= sizeof (errno_tab))
    return EINVAL;
  return errno_tab[rc];
}

